# my global config
global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds.
  evaluation_interval: 5s # Evaluate rules every 15 seconds.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['localhost:9090']

    # Scrape Kafka Connect /metrics
  - job_name: 'kafka-connect-host'
    static_configs:
      - targets: ['kafka-connect:9876']

  - job_name: 'pymetrics-1'
    static_configs:
      - targets: ['connector:8000']
    metrics_path: '/metrics/prometheus-connector-1'

  - job_name: 'pymetrics-2'
    static_configs:
      - targets: [ 'connector:8000' ]
    metrics_path: '/metrics/prometheus-connector-2'

  - job_name: 'pymetrics-3'
    static_configs:
      - targets: [ 'connector:8000' ]
    metrics_path: '/metrics/prometheus-connector-3'
